import type { Metadata } from "next";
import { Google_Sans } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";

// Google Sans font configuration
const googleSans = Google_Sans({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  display: "swap",
});

// Site metadata for SEO
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/**
 * RootLayout - Root layout wrapper for the entire application
 *
 * Provides:
 * - HTML structure and language
 * - Global font configuration (Google Sans)
 * - Persistent Navbar and Footer across all pages
 * - Black background theme
 */
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${googleSans.className} antialiased bg-black`}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
